include: package:very_good_analysis/analysis_options.4.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/main_staging.dart'
    - '**/main_development.dart'
    - '**/main_production.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/firebase_options_dev.dart'
    - '**/firebase_options.dart'