include: package:pedantic/analysis_options.1.9.0.yaml

linter:
  rules:
    require_trailing_commas : true
    prefer_const_declarations : true
    lines_longer_than_80_chars : true
    always_declare_return_types : true
    prefer_final_fields: true
    prefer_single_quotes: true
    file_names: true
    avoid_print: true
