name: times_up_flutter
description: Times up help parent monitor the time their kids spend on screen.
version: 1.0.0+1
publish_to: none


environment:
  sdk: ">=2.16.0 <3.5.0"

dependencies:
  # UI Packages:
  auto_size_text: ^3.0.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_svg: ^2.0.4


  # Authentication Packages:
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  flutter_login_facebook: ^1.4.1

  # Data Management Packages:
  provider: ^6.0.2
  cloud_firestore: ^4.5.0
  shared_preferences: ^2.0.15
  installed_apps: ^1.3.1
  battery_plus: ^4.0.1
  device_info_plus: ^8.2.2
  firebase_storage: ^11.1.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1


  # Location Packages:
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.5

  # Notification Packages:
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^14.0.0-dev.2

  # Utility Packages:
  intl: ^0.18.0
  uuid: ^3.0.6
  app_usage: ^2.0.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.5+3
  after_layout: ^1.2.0
  rename: ^2.1.1

  # UI Component Packages:
  line_awesome_flutter: ^2.0.0
  showcaseview: ^2.0.3
  flutter_any_logo: ^1.0.5

  # Testing Packages:
  mockito: ^5.0.0

  # Share Packages:
  share_plus: ^6.3.0

  # Code Formatting Packages:
  pedantic: ^1.9.2

  test: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  #logger
  logger: ^1.4.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
      - images/facebook-logo.png
      - images/google-logo.png
      - images/splash_svg/
      - images/png/

